### ISSUE TITLE
cannot import name 'AtrousConvolution2D' from 'keras.layers'

### ISSUE THREAD

**Issue by Nicola-Bini** [rykov8/ssd_keras#161]
Error when importing ssd.py, does someone know why?

from ssd import *

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-02bc565461a9> in <module>
----> 1 from ssd import *

~/drive/Assets/Coding/python/inifity_stack_bot_dani/value_recognition/ssd.py in <module>
      3 import keras.backend as K
      4 from keras.layers import Activation
----> 5 from keras.layers import AtrousConvolution2D
      6 from keras.layers import Convolution2D
      7 from keras.layers import Dense

ImportError: cannot import name 'AtrousConvolution2D' from 'keras.layers' (/Users/nicolabini/anaconda3/lib/python3.8/site-packages/keras/layers/__init__.py)

**Comment by helloiloveyouguoshen** [comment]
2022-04-25 20:26:09.841824: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-04-25 20:26:09.841955: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "E:\python Demo\PycharmProjects\pythonProject\数据分析\tf.keras\SDD物体检测\test.py", line 1, in <module>
    from nets import ssd_net
  File "E:\python Demo\PycharmProjects\pythonProject\数据分析\tf.keras\SDD物体检测\nets\ssd_net.py", line 5, in <module>
    from keras.layers import AtrousConvolution2D
ImportError: cannot import name 'AtrousConvolution2D' from 'keras.layers' (E:\python Demo\PycharmProjects\venv\lib\site-packages\keras\layers\__init__.py)

**Comment by yankeee-0411** [comment]
check your keras version, this is no longer support in the latest version
