### ISSUE TITLE
Problem testing on web Cam

### ISSUE THREAD

**Issue by Walid-Ahmed** [rykov8/ssd_keras#26]
Hi.
Thanks a  lot for your SSD implementation, I tested your code in images and worked fine.
But when I tried to apply to a webcam,I changed  vid_test.run('path/to/your/video.mkv')  to vid_test.run(0) and tried also  vid_test.run(), I got the following error

>  python videotest_example.py
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "videotest_example.py", line 25, in <module>
>     vid_test.run()
>   File "/Users/walidahmed/Desktop/Code/ssd_keras-master/testing_utils/videotest.py", line 87, in run
>     vidw = vid.get(cv2.cv.CV_CAP_PROP_FRAME_WIDTH)
> AttributeError: 'module' object has no attribute 'cv'

I have my cv2.__version__  :'3.2.0-dev'

Can you please advice?

Walid

**Comment by Walid-Ahmed** [comment]
Solved, it was an opencv3 issue

    #vidw = vid.get(cv2.cv.CV_CAP_PROP_FRAME_WIDTH)   #CV_CAP_PROP_FRAME_WIDTH 
    vidw = vid.get(cv2.CAP_PROP_FRAME_WIDTH)
    #vidh = vid.get(cv2.cv.CV_CAP_PROP_FRAME_HEIGHT)
    vidh = vid.get(cv2.CAP_PROP_FRAME_HEIGHT)
