### ISSUE TITLE
Unable to find frame01884.png

### ISSUE THREAD

**Issue by nsivaramakrishnan** [rykov8/ssd_keras#33]
Hi,
   I want to run SSD_training.ipynb. I converted that to .py and when I run that, I get the following error. What is that am missing?

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 429, in data_generator_task
    generator_output = next(self._generator)
  File "SSD_training.py", line 204, in generate
    img = imread(img_path).astype('float32')
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2312, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'../../frames/frame01884.png'

Traceback (most recent call last):
  File "SSD_training.py", line 285, in <module>
    nb_worker=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1528, in fit_generator
    str(generator_output))
ValueError: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None

**Comment by rykov8** [comment]
@nsivaramakrishnan I don't provide the dataset, so, you cannot simply run the training loop without changes, it is given only as a reference how to deal with API.
