### ISSUE TITLE
The code is written by tensorflow API, not pure Keras API. It can only run on tensorflow, not theano?

### ISSUE THREAD

**Issue by KevinYuk** [rykov8/ssd_keras#38]
e.g.: ssd_training.py. A lot of code are used by tensorflow API. Not pure keras API.

**Comment by rykov8** [comment]
@KevinYuk yes, you're right. Forward pass should work with `Theano` backend also but I've never tested it. Training part is `Tensorflow` only because of the lack of some methods in `Keras` backend.

**Comment by KevinYuk** [comment]
@rykov8 Thanks for your response and and great work.
I try to run forward code on theano, it seems that something wrong. I can run the forward by the keras config below(backend is theano, but image_dim_ordering is th. Or it can not run):
```
{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
```
But it cannot correctly predict the picture as tensorflow.

I found that ssd.py code is written by keras API, but ssd_layers.py and ssd_utils.py are written by tf API(Just focus on froward, not trainning).
E.g.: In ssd_layers.py, I found the code below:
```
        if K.backend() == 'tensorflow':
            pattern = [tf.shape(x)[0], 1, 1]
            prior_boxes_tensor = tf.tile(prior_boxes_tensor, pattern)
        elif K.backend() == 'theano':
            #TODO
            pass
        return prior_boxes_tensor
```
It seems that theano is not implemented. Is that Ok? Or do you have any idea how to fix it?

Thanks again for your great work!!!

**Comment by arunreddy** [comment]
@KevinYuk @rykov8 

Thanks a lot for porting SSD to keras. Using the bleeding edge theano I was able to get the SSD example working. But the detection is not bad. Is it a bug due to lack of theano support?

Please refer the screenshot:

![screenshot from 2017-02-16 21-50-43](https://cloud.githubusercontent.com/assets/149593/23052914/69ac4bd4-f492-11e6-83e7-1f47b6da01e2.png)

**Comment by KevinYuk** [comment]
@arunreddy I can also get the same result as you. But that's not right. You can check your code, you will find that it still run on the tensorflow, not theano. You keras config is like below, right?
```
{
    "image_dim_ordering": "tf",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
```
But image_dim_ordering=tf will direct the code logic go to the tensorflow, not theano.
```
class Convolution2D(Layer):
    '''Convolution operator for filtering windows of two-dimensional inputs.
    When using this layer as the first layer in a model,
    provide the keyword argument `input_shape`
    (tuple of integers, does not include the sample axis),
    e.g. `input_shape=(3, 128, 128)` for 128x128 RGB pictures.

    # Examples

    ```python
        # apply a 3x3 convolution with 64 output filters on a 256x256 image:
        model = Sequential()
        model.add(Convolution2D(64, 3, 3, border_mode='same', input_shape=(3, 256, 256)))
        # now model.output_shape == (None, 64, 256, 256)

        # add a 3x3 convolution on top, with 32 output filters:
        model.add(Convolution2D(32, 3, 3, border_mode='same'))
        # now model.output_shape == (None, 32, 256, 256)
    ```

    # Arguments
        nb_filter: Number of convolution filters to use.
        nb_row: Number of rows in the convolution kernel.
        nb_col: Number of columns in the convolution kernel.
        init: name of initialization function for the weights of the layer
            (see [initializations](../initializations.md)), or alternatively,
            Theano function to use for weights initialization.
            This parameter is only relevant if you don't pass
            a `weights` argument.
        activation: name of activation function to use
            (see [activations](../activations.md)),
            or alternatively, elementwise Theano function.
            If you don't specify anything, no activation is applied
            (ie. "linear" activation: a(x) = x).
        weights: list of numpy arrays to set as initial weights.
        border_mode: 'valid' or 'same'.
        subsample: tuple of length 2. Factor by which to subsample output.
            Also called strides elsewhere.
        W_regularizer: instance of [WeightRegularizer](../regularizers.md)
            (eg. L1 or L2 regularization), applied to the main weights matrix.
        b_regularizer: instance of [WeightRegularizer](../regularizers.md),
            applied to the bias.
        activity_regularizer: instance of [ActivityRegularizer](../regularizers.md),
            applied to the network output.
        W_constraint: instance of the [constraints](../constraints.md) module
            (eg. maxnorm, nonneg), applied to the main weights matrix.
        b_constraint: instance of the [constraints](../constraints.md) module,
            applied to the bias.
        dim_ordering: 'th' or 'tf'. In 'th' mode, the channels dimension
            (the depth) is at index 1, in 'tf' mode is it at index 3.
            It defaults to the `image_dim_ordering` value found in your
            Keras config file at `~/.keras/keras.json`.
            If you never set it, then it will be "tf".
        bias: whether to include a bias
            (i.e. make the layer affine rather than linear).

    # Input shape
        4D tensor with shape:
        `(samples, channels, rows, cols)` if dim_ordering='th'
        or 4D tensor with shape:
        `(samples, rows, cols, channels)` if dim_ordering='tf'.

    # Output shape
        4D tensor with shape:
        `(samples, nb_filter, new_rows, new_cols)` if dim_ordering='th'
        or 4D tensor with shape:
        `(samples, new_rows, new_cols, nb_filter)` if dim_ordering='tf'.
        `rows` and `cols` values might have changed due to padding.
    '''
    def __init__(self, nb_filter, nb_row, nb_col,
                 init='glorot_uniform', activation='linear', weights=None,
                 border_mode='valid', subsample=(1, 1), dim_ordering='default',
                 W_regularizer=None, b_regularizer=None, activity_regularizer=None,
                 W_constraint=None, b_constraint=None,
                 bias=True, **kwargs):
        if dim_ordering == 'default':
            dim_ordering = K.image_dim_ordering()
```

image_dim_ordering will direct you code run theano.

**Comment by rykov8** [comment]
@KevinYuk sorry, I forgot about `ssd_layers.py` and `ssd_utils.py`, I am afraid, you'll have to reimplement the necessary parts in `Theano`, in case of `ssd_layers.py` it should be simple. You just need to right the similar thing to
```python
pattern = [tf.shape(x)[0], 1, 1]
prior_boxes_tensor = tf.tile(prior_boxes_tensor, pattern)
```
in `Theano` under the appropriate brach of `if-else`. Probably, there can be a simple fix using `Keras` backend also, I will examine it later, or you can make a PR, if you manage to fix it. In case of `ssd_utils.py` the situation is more complicated, because here I rely on `tf.image.non_max_suppression` that is definitely not presented in `Keras` backend, so, you need to reimplement this part in pure `Theano`.

@KevinYuk @arunreddy I believe, the problem lies in convolutional weights. As you know, actually `Theano` performs vanilla [convolution](https://en.wikipedia.org/wiki/Convolution), but `Tensorflow` performs  [cross-correlation](https://en.wikipedia.org/wiki/Cross-correlation). But it is quite simple to fix: you just need to flip the kernels like:
```python
theano_kernel = tf_kernel[::-1, ::-1, :, :]
```
Then you need to transpose the kernel in order to match `Theano` dim_ordering, probably like this:
```python
theano_kernel = theano_kernel.transpose(2, 3, 0, 1)
```
Please, check the correct order of axes in `Theano`, here I assume them to be (old_channels, new_channels, width, height), but probably, I'm wrong. I believe, that [here](https://github.com/fchollet/keras/blob/master/keras/applications/vgg16.py) is the example of kernel changing.

**Comment by KevinYuk** [comment]
@rykov8 Thanks for your valuable input. If you could finish the theano version, that would be better.
Let me summarize the work if we want to enable the **foward(aka: inference)** of SSD on theano.
1. complete the code for theano in ssd_layers.py file. Only include the last several lines;
2. re-implement non max suppression algorithm by theano API; Then we can use it in ssd_utils.py file;
3. adjust convolutional weights.

Still there are some question below, please help check them:
Q1. in ssd_layers.py file, we just need complete below code, nothing else?
```
......
        elif K.backend() == 'theano':
            #TODO
            pass
        return prior_boxes_tensor
```
Q2. in ssd_utils.py file, we just need re-implement non max suppression algorithm by theano API and replace it from tf API to theano, nothing else? I found that there are decode_boxes, encode_box, assign_boxes , iou fuctions and so on. We just keep them same, right?
Q3. in ssd_utils.py file, some var are initialized by tf API like below:
```
        self.boxes = tf.placeholder(dtype='float32', shape=(None, 4))
        self.scores = tf.placeholder(dtype='float32', shape=(None,))
```
should we concern it or not?
Q4. Regarding to convolutional weights, do we need modify weights_SSD300.hdf5 for theano? Or just keep it the same as before? I have found that theano arch don't recognize it.
`ValueError: Input dimension mis-match. (input[0].shape[1] = 3, input[1].shape[1] = 64)`
Q5. Regarding to prior_boxes_ssd300.pkl, I find that it only has relationship with ssd network topology. However, if I directly use it in theano, is it still ok?


Thanks a lot.
Kevin.

**Comment by oscfri** [comment]
Any progress of this issue? I'm also trying to get this code work with Theano but has stumbled into the same issues.

**Comment by KevinYuk** [comment]
@oscfri 
I believe we can successfully run inference of SSD based on theano if we follow below steps(but now, I am afraid that I don't have so much time to implement it):
1. convert weights_SSD300.hdf5 from tensorflow shape to theano shape(I have successfully convert it, the code is at the end of this coment);
2. re-implement the two SSD layers from ssd_layers.py. They are Normalize and PriorBox layers which is used by ssd.py models;
3. re-implement the BBox function from ssd_utils.py. The origin code is written by tensorflow.

So many works to do if we want to use it on theao.


Note: code for convert weights(I have successfully do that):
```
import h5py
import numpy as np

dst_f = h5py.File("th_weights_SSD300.hdf5", "w")
###add attr first
grp_list = ['conv1_1', 'conv1_2', 'conv2_1', 'conv2_2', 'conv3_1', 'conv3_2', 'conv3_3', 'conv4_1', 'conv4_2', 'conv4_3', 'conv4_3_norm', 'conv4_3_norm_mbox_conf', 'conv4_3_norm_mbox_conf_flat', 'conv4_3_norm_mbox_loc', 'conv4_3_norm_mbox_loc_flat', 'conv4_3_norm_mbox_priorbox', 'conv5_1', 'conv5_2', 'conv5_3', 'conv6_1', 'conv6_2', 'conv6_2_mbox_conf', 'conv6_2_mbox_conf_flat', 'conv6_2_mbox_loc', 'conv6_2_mbox_loc_flat', 'conv6_2_mbox_priorbox', 'conv7_1', 'conv7_2', 'conv7_2_mbox_conf', 'conv7_2_mbox_conf_flat', 'conv7_2_mbox_loc', 'conv7_2_mbox_loc_flat', 'conv7_2_mbox_priorbox', 'conv8_1', 'conv8_2', 'conv8_2_mbox_conf', 'conv8_2_mbox_conf_flat', 'conv8_2_mbox_loc', 'conv8_2_mbox_loc_flat', 'conv8_2_mbox_priorbox', 'fc6', 'fc7', 'fc7_mbox_conf', 'fc7_mbox_conf_flat', 'fc7_mbox_loc', 'fc7_mbox_loc_flat', 'fc7_mbox_priorbox', 'input_2', 'mbox_conf', 'mbox_conf_final', 'mbox_conf_logits', 'mbox_loc', 'mbox_loc_final', 'mbox_priorbox', 'pool1', 'pool2', 'pool3', 'pool4', 'pool5', 'pool6', 'pool6_mbox_conf_flat', 'pool6_mbox_loc_flat', 'pool6_mbox_priorbox', 'pool6_reshaped', 'predictions', 'zeropadding2d_3']
dst_f.attrs['layer_names'] = grp_list

###read src weights_SSD300.hdf5
src_f = h5py.File("weights_SSD300.hdf5")
#visit each group
for grp in grp_list:
    dset = src_f[grp]
    attr_data_list = dset.attrs['weight_names']
    #create grp first
    dst_grp = dst_f.create_group(grp)
    #create grp attributes
    dst_grp.attrs['weight_names'] = attr_data_list
    for attr_data in attr_data_list:
        dataset_name = grp + '/' + attr_data
        dset1 = src_f[dataset_name]
        if 4 == dset1.ndim:
            #convert from hdf5 to numpy data format
            np_dat = np.array(dset1)
            #transpose and reshape
            idx0 = 3
            idx1 = 2
            idx2 = 0
            idx3 = 1
            np_dat = np.transpose(np_dat, (idx0, idx1, idx2, idx3)).reshape(np_dat.shape[idx0], np_dat.shape[idx1], np_dat.shape[idx2], np_dat.shape[idx3])
            #write it back to dst_f hdf5
            dset2 = dst_f.create_dataset(dataset_name, data=np_dat)
            #print np_dat
        else:
            np_dat = np.array(dset1)
            dset2 = dst_f.create_dataset(dataset_name, data=np_dat)
```

**Comment by oscfri** [comment]
Thanks! I will see if I can manage to implement step 2 and 3.

**Comment by bsrinivas8687** [comment]
@rykov8 

I am unable to load the model with 'th' image_dim_ordering and 'tensorflow' backend;

```Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "./test.py", line 30, in <module>
    model = SSD300(input_shape, num_classes=NUM_CLASSES)
  File "/home/dummy/ssd_keras/ssd.py", line 77, in SSD300
    net['conv4_3_norm'] = Normalize(20, name='conv4_3_norm')(net['conv4_3'])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/dummy/ssd_keras/ssd_layers.py", line 43, in call
    output *= self.gamma
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 814, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 987, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1613, in mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 38 and 512 for 'mul' (op: 'Mul') with input shapes: [?,512,38,38], [512].```

Is there any way to use model with 'th' image_dim_order?

**Comment by bsrinivas8687** [comment]
I am unable to load model with 'th' image_dim_ordering and 'tensorflow' backend.

```
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "./test.py", line 30, in <module>
    model = SSD300(input_shape, num_classes=NUM_CLASSES)
  File "/home/dummy/ssd_keras/ssd.py", line 77, in SSD300
    net['conv4_3_norm'] = Normalize(20, name='conv4_3_norm')(net['conv4_3'])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/dummy/ssd_keras/ssd_layers.py", line 43, in call
    output *= self.gamma
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 814, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 987, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1613, in mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 38 and 512 for 'mul' (op: 'Mul') with input shapes: [?,512,38,38], [512].
```

Is there any way to use model with 'th' image_dim_order?
