### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../frames/frame02579.png'

### ISSUE THREAD

**Issue by vorale** [rykov8/ssd_keras#47]
I am getting a file not found error in generate function of file SSD_Training.ipynb, complaining a file is not found.

the stack trace is as below:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/vorale/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/vorale/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vorale/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 429, in data_generator_task
    generator_output = next(self._generator)
  File "/home/vorale/Downloads/ssd_keras-master/ssd_training2.py", line 186, in generate
    img = imread(img_path).astype('float32')
  File "/home/vorale/anaconda3/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/home/vorale/anaconda3/lib/python3.5/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../../frames/frame02579.png'
```

Is there any folder I haven't included?

**Comment by rykov8** [comment]
Training images are not provided, as they are part of my dataset, that is not public.

**Comment by dremovd** [comment]
Is this right, that dataset you use is compatible with PASCAL dataset format?
