### ISSUE TITLE
Training Problem 

### ISSUE THREAD

**Issue by eric82714** [rykov8/ssd_keras#51]
Hi @rykov8, I have a training error when I train my own image dataset.
1120/1133 [============================>.] - ETA: 15s - loss: 1.8311Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 404, in data_generator_task
    generator_output = next(generator)
  File "/home/optsai/文件/Object detection/training(fine-tune).py", line 169, in generate
    img = imread(img_path).astype('float32')
TypeError: float() argument must be a string or a number

Do you meet this error before??

**Comment by rykov8** [comment]
@eric82714 probably, there is some problem in the path to the image? I have never met this before, sorry.

**Comment by eric82714** [comment]
@rykov8  I have solved this error. Thank you!

**Comment by saadyousuf45** [comment]
How did you solve it????
