### ISSUE TITLE
path_prefix = '../../frames/' ?

### ISSUE THREAD

**Issue by flpgrz** [rykov8/ssd_keras#73]
Hey guys,

if I try to train the model with SSD_training.ipynb on the standard training set, I get the following error:

```
nb_epoch = 30

history = model.fit_generator(gen.generate(True), gen.train_batches,

                              nb_epoch, verbose=1,

                              callbacks=callbacks,

                              validation_data=gen.generate(False),

                              nb_val_samples=gen.val_batches,

                              nb_worker=1)

```
```
/home/filippo/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:7: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., 4651, 30, validation_steps=1163, validation_data=<generator..., callbacks=[<keras.ca..., workers=1, verbose=1)`
/home/filippo/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:91: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/home/filippo/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/filippo/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/filippo/.local/lib/python3.5/site-packages/keras/engine/training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
  File "<ipython-input-8-0501eef3a2f4>", line 144, in generate
    img = imread(img_path).astype('float32')
  File "/home/filippo/.local/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/home/filippo/anaconda3/lib/python3.5/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../../frames/frame01991.png'

```
```
Epoch 1/30

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-d1cddf4cd3eb> in <module>()
      5                               validation_data=gen.generate(False),
      6                               nb_val_samples=gen.val_batches,
----> 7                               nb_worker=1)

/home/filippo/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     86                 warnings.warn('Update your `' + object_name +
     87                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 88             return func(*args, **kwargs)
     89         wrapper._legacy_support_signature = inspect.getargspec(func)
     90         return wrapper

/home/filippo/.local/lib/python3.5/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_q_size, workers, pickle_safe, initial_epoch)
   1850                                          'a tuple `(x, y, sample_weight)` '
   1851                                          'or `(x, y)`. Found: ' +
-> 1852                                          str(generator_output))
   1853                     if len(generator_output) == 2:
   1854                         x, y = generator_output

ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None


```
Do you know how to solve it? I think it's simply because I don't have this "../../frames/" folder, however I don't know what it is supposed to contain. 
Thanks a lot in advance,
Filippo

**Comment by flpgrz** [comment]
Solution: 

https://github.com/rykov8/ssd_keras/issues/47
